export const EMOJI_MAP = [
  { name: "액션가면", id: 28 },
  { name: "모험가", id: 12 },
  { name: "수사대장", id: 80 },
  { name: "사랑꾼", id: 10749 },
  { name: "웃음사냥꾼", id: 35 },
  { name: "호그와트생", id: 14 },
  { name: "유명한탐정", id: 9648 },
  { name: "신비주의", id: 878 },
  { name: "소오름", id: 27 },
  { name: "현생러", id: 99 },
  { name: "파이브덕", id: 16 },
  { name: "굿리스너", id: 10402 },
  { name: "드라마틱", id: 18 },
  { name: "따뜻한마음", id: 10751 },
  { name: "고고학자", id: 36 },
  { name: "티-브이", id: 10770 },
  { name: "강심장", id: 53 },
  { name: "밀덕", id: 10752 },
  { name: "뱅뱅뱅", id: 37 },
];
