import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import type { Metadata } from "next";

import GoogleAnalytics from "@/components/googleanalytics/GoogleAnalytics";
import Header from "@/components/header/Header";
import HeaderContainer from "@/components/header/HeaderContainer";
import ReactQueryProvier from "@/react-query/ReactQueryProvider";
import { appleSDGothicNeo, pretendard } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
        <meta
          name="viewport"
          content="initial-scale=1.0, user-scalable=no, maximum-scale=1, width=device-width"
        />
      </head>
      <body className={`${pretendard.variable} ${appleSDGothicNeo.variable}`}>
        <ReactQueryProvier>
          <HeaderContainer />
          {children}
          <div id="portal" />
        </ReactQueryProvier>
        {process.env.REACT_APP_GA_TRACKING_ID ? (
          <GoogleAnalytics gaId={process.env.REACT_APP_GA_TRACKING_ID} />
        ) : null}
      </body>
    </html>
  );
}
